# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-19 17:05
from __future__ import unicode_literals

import custom_storage.vendr_storage
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import kproperty.models.property_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Historical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_sold_price', models.FloatField(blank=True, null=True)),
                ('last_sold_date', models.DateField(blank=True, null=True)),
                ('year_built', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, max_length=150, null=True, storage=custom_storage.vendr_storage.VendrMediaStorage(), upload_to=kproperty.models.property_fields.listing_file_name)),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(db_index=True, max_length=50)),
                ('province', models.CharField(db_index=True, max_length=20)),
                ('city', models.CharField(db_index=True, max_length=30)),
                ('address', models.CharField(db_index=True, max_length=100)),
                ('postal_code', models.CharField(db_index=True, max_length=10)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='OpenHouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(db_index=True)),
                ('sqr_ftg', models.FloatField(db_index=True)),
                ('n_bedrooms', models.IntegerField(db_index=True)),
                ('n_bathrooms', models.IntegerField(db_index=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('views', models.IntegerField(default=0)),
                ('offers', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, max_length=350, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaxRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment', models.FloatField(blank=True, null=True)),
                ('assessment_year', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CoOp',
            fields=[
                ('property_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kproperty.Property')),
                ('unit_num', models.IntegerField()),
            ],
            bases=('kproperty.property',),
        ),
        migrations.CreateModel(
            name='Freehold',
            fields=[
                ('property_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kproperty.Property')),
            ],
            bases=('kproperty.property',),
        ),
        migrations.AddField(
            model_name='taxrecords',
            name='kproperty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_records', to='kproperty.Property'),
        ),
        migrations.AddField(
            model_name='property',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='location',
            name='kproperty',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='kproperty.Property'),
        ),
        migrations.AddField(
            model_name='images',
            name='kproperty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='kproperty.Property'),
        ),
        migrations.AddField(
            model_name='historical',
            name='kproperty',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='kproperty.Property'),
        ),
        migrations.AddField(
            model_name='features',
            name='kproperty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='kproperty.Property'),
        ),
        migrations.CreateModel(
            name='Condo',
            fields=[
                ('coop_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kproperty.CoOp')),
            ],
            bases=('kproperty.coop',),
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('freehold_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kproperty.Freehold')),
            ],
            bases=('kproperty.freehold',),
        ),
        migrations.CreateModel(
            name='Multiplex',
            fields=[
                ('freehold_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kproperty.Freehold')),
                ('degree', models.IntegerField()),
            ],
            bases=('kproperty.freehold',),
        ),
    ]
