# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kproperty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='condo',
            name='floor_num',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
