# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-19 17:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kproperty', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Multiplex',
            new_name='Townhouse',
        ),
    ]
