# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 19:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kproperty', '0002_condo_floor_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
                ('province', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('postal_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='kproperty.Location'),
        ),
    ]
