# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kproperty', '0004_auto_20170627_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coop',
            name='unit_num',
            field=models.CharField(max_length=8),
        ),
    ]
