# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-31 19:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kproperty', '0006_location_geo_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coop',
            name='unit_num',
        ),
    ]
