# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-31 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kproperty', '0007_remove_coop_unit_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='coop',
            name='unit_num',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
