# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-31 23:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kproperty', '0008_coop_unit_num'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OpenHouse',
        ),
    ]
