# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-01 00:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kproperty', '0010_openhouse_rsvp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rsvp',
            old_name='kuser',
            new_name='owner',
        ),
        migrations.AddField(
            model_name='openhouse',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='openhouse',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('0f9b557d-c921-42df-9ddc-f13d56beb4d9'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('6f01413a-a8a7-4263-858a-b786f141f2fe'), editable=False, primary_key=True, serialize=False),
        ),
    ]
