# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 23:41
from __future__ import unicode_literals

import custom_storage.vendr_storage
from django.db import migrations, models
import kuser.models.user


class Migration(migrations.Migration):

    dependencies = [
        ('kuser', '0007_transactionnotification_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='prof_pic',
            field=models.ImageField(blank=True, max_length=150, null=True, storage=custom_storage.vendr_storage.VendrMediaStorage(), upload_to=kuser.models.user.prof_pic_file_name),
        ),
    ]
