# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-19 18:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kproperty', '0002_auto_20170619_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufactured',
            fields=[
                ('property_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kproperty.Property')),
            ],
            bases=('kproperty.property',),
        ),
        migrations.CreateModel(
            name='VacantLand',
            fields=[
                ('property_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kproperty.Property')),
            ],
            bases=('kproperty.property',),
        ),
    ]
