# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kproperty', '0003_manufactured_vacantland'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(db_index=True, decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(db_index=True, decimal_places=6, max_digits=9),
        ),
    ]
