# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-31 23:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kproperty', '0009_delete_openhouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenHouse',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.UUID('af0b2424-d373-4e4d-9d82-632bf77dd4dc'), editable=False, primary_key=True, serialize=False)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('kproperty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_house', to='kproperty.Property')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RSVP',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.UUID('fd64abee-3ca4-43b0-bd39-0588ff162c81'), editable=False, primary_key=True, serialize=False)),
                ('kuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('open_house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvp_list', to='kproperty.OpenHouse')),
            ],
        ),
    ]
