# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-01 00:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('kproperty', '0011_auto_20170801_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openhouse',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('4f6e4298-f12d-4c7b-9efb-f4bfc0379ce1'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('c8a75066-e962-46cc-8696-e60301c68d75'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='open_house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_house', to='kproperty.OpenHouse'),
        ),
    ]
