# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-04 18:32
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('kproperty', '0012_auto_20170801_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openhouse',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
