# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-19 17:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kuser', '0002_auto_20170619_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kuser',
            name='uuid',
        ),
    ]
