# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 22:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kuser', '0004_remove_offernotification_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionnotification',
            name='transaction',
        ),
    ]
