# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuser', '0005_remove_transactionnotification_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='offernotification',
            name='offer',
            field=models.UUIDField(default='45b032ef-1832-4966-bc0c-b117568bae19'),
            preserve_default=False,
        ),
    ]
