# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-30 23:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kuser', '0012_kuser_favourites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kuser',
            name='favourites',
        ),
    ]
