# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-19 19:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacantLandContract',
            fields=[
                ('contract_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transaction.Contract')),
            ],
            bases=('transaction.contract',),
        ),
        migrations.RenameModel(
            old_name='MobileContract',
            new_name='ManufacturedContract',
        ),
    ]
