# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 19:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_townhousecontract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='buyer_accepted_contract',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='seller_accepted_contract',
        ),
    ]
