# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-01 19:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transaction', '0006_auto_20170427_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=150)),
                ('is_viewed', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContractNotification',
            fields=[
                ('transactionnotification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notification.TransactionNotification')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='transaction.Contract')),
            ],
            options={
                'abstract': False,
            },
            bases=('notification.transactionnotification',),
        ),
        migrations.CreateModel(
            name='OfferNotification',
            fields=[
                ('transactionnotification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notification.TransactionNotification')),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='transaction.Offer')),
            ],
            options={
                'abstract': False,
            },
            bases=('notification.transactionnotification',),
        ),
        migrations.AddField(
            model_name='transactionnotification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transactionnotification',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='transaction.Transaction'),
        ),
    ]
