# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-03 16:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractnotification',
            name='contract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='transaction.Contract'),
        ),
        migrations.AlterField(
            model_name='offernotification',
            name='offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='transaction.Offer'),
        ),
        migrations.AlterField(
            model_name='transactionnotification',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='transaction.Transaction'),
        ),
    ]
