# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 21:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kproperty', '0009_auto_20170316_1658'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.IntegerField(choices=[(0, 'OFFER_STAGE'), (1, 'NEGOTIATION_STAGE'), (2, 'CLOSE_STAGE')])),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to=settings.AUTH_USER_MODEL)),
                ('kproperty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property', to='kproperty.Property')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
