# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-19 19:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_auto_20170619_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='potlfreeholdcontract',
            name='freeholdcontract_ptr',
        ),
        migrations.DeleteModel(
            name='POTLFreeholdContract',
        ),
    ]
