# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-19 19:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_auto_20170619_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='TownhouseContract',
            fields=[
                ('housecontract_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transaction.HouseContract')),
            ],
            bases=('transaction.housecontract',),
        ),
    ]
