# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0007_auto_20170705_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='contracts_equal',
            field=models.BooleanField(default=False),
        ),
    ]
