# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0009_transaction__dampen'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='_fired',
            field=models.BooleanField(default=False),
        ),
    ]
